name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x]
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    steps:
      - name: Pull sources
        uses: actions/checkout@v2
    
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run tests
        run: npm test
